### ISSUE TITLE
Latest commits breaks lazy-connect

### ISSUE THREAD

**Issue by NithyaNatarajan** [arunvelsriram/lazy-connect#12]
Issue:

After modifying `lazy-connect.sh` to  `lazy-connect` in .bashrc to accommodate the latest changes, `lazy-connect` always opens by default.

<img width="1440" alt="screen shot 2018-11-02 at 10 52 04 am" src="https://user-images.githubusercontent.com/1219699/47893017-5acdec80-de8d-11e8-8436-4d29558484cf.png">

**Comment by arunvelsriram** [comment]
`master` branch is broken now due to a change introduced for making `lazy-connect` available via `brew`. Please use tag `v1.4.0`.

**Comment by arunvelsriram** [comment]
@jskswamy is working on the fix.
