### ISSUE TITLE
Documentation to be updated after the latest commits

### ISSUE THREAD

**Issue by NithyaNatarajan** [arunvelsriram/lazy-connect#13]
The documentation says 

`echo "[ -f ~/.lazy-connect/lazy-connect.sh ] && source ~/.lazy-connect/lazy-connect.sh" ` but `lazy-connect.sh` has been modified to `lazy-connect` in latest release.

**Comment by arunvelsriram** [comment]
`master` branch is broken now due to a change introduced for making `lazy-connect` available via `brew`. Please use tag `v1.4.0` for now.

**Comment by arunvelsriram** [comment]
@jskswamy is working on the fix.
