### ISSUE TITLE
Sometimes the authenticator code is not entered in the VPN Connection modal. 

### ISSUE THREAD

**Issue by krarjun90** [arunvelsriram/lazy-connect#15]
Sometimes the authenticator code is not entered in the VPN Connection modal. Please see the screenshot. This happens when the modal takes few extra seconds to load. 

<img width="939" alt="screen shot 2018-11-15 at 2 04 34 pm" src="https://user-images.githubusercontent.com/1826412/48540240-96ca6e00-e8df-11e8-8824-443f42e92b39.png">

**Comment by arunvelsriram** [comment]
This will happen when the internet is a bit slow. The reason for this is the hardcoded time delay here: https://github.com/arunvelsriram/lazy-connect/blob/master/lazy-connect#L121

I can increase this delay to 2 seconds.

#6 has a workaround for this. Its yet to be merged

**Comment by arunvelsriram** [comment]
Please upgrade to latest version and check.

**Comment by arunvelsriram** [comment]
Fixed by  #16
